name: Build & test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        c_compiler: [clang]
        build_type: [Debug, Release]
        cxx_standard: ["20"]
        include:
          - c_compiler: clang
            cxx_compiler: clang++

    name: ${{ matrix.c_compiler }} - ${{ matrix.build_type }} - ${{ matrix.os }} - c++${{ matrix.cxx_standard }}
        
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install conan
      shell: bash
      run: |
        pip install conan

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Cache LLVM library
      id: cache-llvm-library
      uses: actions/cache@v3
      with:
        path: ${{runner.workspace}}/build/externals/LLVM/install
        key: llvm-cache-${{ matrix.c_compiler }}-${{ matrix.build_type }}-${{ matrix.os }}-c++${{ matrix.cxx_standard }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      env:
        CC: ${{matrix.c_compiler}}
        CXX: ${{matrix.cxx_compiler}}
      run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DEXTERNAL_LLVM_BUILD_TYPE:STRING=Release

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        ./bin/TestAST
        ./bin/TestPasses
        ./bin/TestIntegration
