name: Build & test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        c_compiler: [clang, cl]
        build_type: [Debug, Release]
        cxx_standard: ["20"]
        include:
          - c_compiler: clang
            cxx_compiler: clang++
          - c_compiler: cl
            cxx_compiler: cl
        exclude:
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    name: ${{ matrix.c_compiler }} - ${{ matrix.build_type }} - ${{ matrix.os }} - c++${{ matrix.cxx_standard }}
        
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: seanmiddleditch/gha-setup-vsdevenv@master

    - name: Install conan
      run: |
        pipx install conan

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Cache LLVM library
      id: cache-llvm-library
      uses: actions/cache@v3
      with:
        path: ${{runner.workspace}}/build/externals/LLVM/install
        key: llvm-cache-${{ matrix.c_compiler }}-${{ matrix.build_type }}-${{ matrix.os }}-c++${{ matrix.cxx_standard }}

    - name: Build LLVM Library
      if: steps.cache-llvm-library.outputs.cache-hit != 'true'
      env:
        CC: ${{matrix.c_compiler}}
        CXX: ${{matrix.cxx_compiler}}
      run: |
        cmake -E make_directory ${{runner.workspace}}/build/externals/LLVM
        cmake -S ${{github.workspace}}/externals/LLVM -B ${{runner.workspace}}/build/externals/LLVM -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DSTRIP_DEBUG_INFO:BOOL=ON
        cmake --build ${{runner.workspace}}/build/externals/LLVM --parallel

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      env:
        MLIR_DIR: ${{runner.workspace}}/build/externals/LLVM/install/lib/cmake/mlir
        LLVM_DIR: ${{runner.workspace}}/build/externals/LLVM/install/lib/cmake/llvm
        CC: ${{matrix.c_compiler}}
        CXX: ${{matrix.cxx_compiler}}
      run: cmake -S ${{github.workspace}} -B ${{runner.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DEXTERNAL_LLVM_STRIP_DEBUG_INFO:BOOL=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Build Python package
      working-directory: ${{runner.workspace}}/build
      env:
        MLIR_DIR: ${{runner.workspace}}/build/externals/LLVM/install/lib/cmake/mlir
        LLVM_DIR: ${{runner.workspace}}/build/externals/LLVM/install/lib/cmake/llvm
        CC: ${{matrix.c_compiler}}
        CXX: ${{matrix.cxx_compiler}}
        CMAKE_BUILD_TYPE: ${{matrix.build_type}}
        CMAKE_CXX_STANDARD: ${{ matrix.cxx_standard }}
      run: |
        pip install ${{github.workspace}}
        pip install -r ${{github.workspace}}/python/requirements-dev.txt      

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: |
        ./bin/TestAST
        ./bin/TestPasses
        ./bin/TestIntegration
        pytest ${{github.workspace}}/python/test
