name: Clang-Format
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0"
      - name: Verify formatting
        run: |
          python ./support/run-clang-format.py -r python
          python ./support/run-clang-format.py -r src
          python ./support/run-clang-format.py -r test